apiVersion: batch/v1
kind: CronJob
metadata:
  name: job1
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa1
          containers:
          - name: check-pending-pod
            image: bitnami/kubectl
            command:
            - "/bin/sh"
            - "-c"
            - "kubectl get pods --field-selector=status.phase=Pending"
          restartPolicy: OnFailure